import {cases,filterCases} from './data.js';
const $=s=>document.querySelector(s);
const STORAGE='shapefolio.favorites.v1';
let saved=[];try{const value=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(Array.isArray(value))saved=[...new Set(value.filter(id=>cases.some(c=>c.id===id)))];}catch{}
const state={category:'全部',query:'',savedOnly:false,sort:'curated'};
let toastTimer;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function artwork(c){return `<div class="artwork ${c.art}" style="--cover-color:${c.color}" aria-hidden="true"><div class="poster-top"><strong>${escape(c.name)}</strong><span>VISUAL STUDY / ${String(cases.indexOf(c)+1).padStart(2,'0')}</span></div><div class="poster-title">${escape(c.headline)}</div><div class="poster-shape"></div><div class="poster-bottom"><span>${escape(c.small)}</span><span>SHAPEFOLIO<br>ORIGINAL COVER</span></div></div>`}
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2200)}
function syncSaves(){document.querySelectorAll('[data-save]').forEach(b=>{const active=saved.includes(b.dataset.save);b.setAttribute('aria-pressed',String(active));b.setAttribute('aria-label',`${active?'取消收藏':'收藏'} ${cases.find(c=>c.id===b.dataset.save).name}`);b.textContent=b.classList.contains('save-button')?(active?'♥':'♡'):(active?'♥ 已收藏':'♡ 收藏作品')});$('#saved-count').textContent=saved.length}
function render(){const visible=filterCases(cases,{...state,saved});$('#cards').innerHTML=visible.map(c=>`<article class="card"><button class="cover-button" data-detail="${c.id}" aria-label="查看 ${escape(c.name)} 的设计笔记">${artwork(c)}<span class="open-hint">设计笔记 ↗</span></button><div class="card-meta"><div><div class="card-title-row"><h3>${escape(c.name)}</h3><span>${escape(c.category)}</span></div><p class="card-description">${escape(c.subtitle)}</p><div class="tags">${c.tags.map(t=>`<span class="tag">${escape(t)}</span>`).join('')}</div></div><button class="save-button" data-save="${c.id}"></button></div></article>`).join('');$('#empty').hidden=visible.length>0;$('#empty-text').textContent=state.savedOnly&&!saved.length?'收藏喜欢的作品，它们就会留在这里。':'换一个关键词，或看看全部作品。';$('#result-count').textContent=`${state.savedOnly?'我的收藏':'精选作品'} / ${String(visible.length).padStart(2,'0')}`;$('#saved-filter').setAttribute('aria-pressed',String(state.savedOnly));document.querySelectorAll('[data-category]').forEach(b=>{const active=b.dataset.category===state.category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});syncSaves()}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];let persisted=true;try{localStorage.setItem(STORAGE,JSON.stringify(saved))}catch{persisted=false}if(state.savedOnly){const focus=document.activeElement;const wasCard=focus?.closest('.card');render();if(wasCard)($('#cards button')||$('#reset')).focus()}else syncSaves();notify(persisted?(saved.includes(id)?'已收进你的灵感收藏':'已取消收藏'):'浏览器无法保存数据；收藏仅在本次页面有效')}
function showDetail(id){const c=cases.find(x=>x.id===id);$('#detail-content').innerHTML=`<div class="detail-art">${artwork(c)}</div><div class="detail-body"><p class="eyebrow">DESIGN NOTES / ${escape(c.category)}</p><h2 id="detail-title">${escape(c.name)} <span style="color:var(--orange)">↗</span></h2><p>${escape(c.note)}</p><p class="lesson">${escape(c.lesson)}</p><div class="tags">${c.tags.map(t=>`<span class="tag">${escape(t)}</span>`).join('')}</div><div class="detail-actions"><a class="dark-button" href="${c.url}" target="_blank" rel="noopener noreferrer">访问原站 ↗</a><button data-save="${c.id}"></button></div><p class="source-caption">来源：${escape(new URL(c.url).hostname)} · 收录核验 2026.10.04<br>封面为原创艺术演绎，非官网截图。笔记为编辑学习建议。</p></div>`;syncSaves();$('#detail').showModal()}
$('#cards').addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.detail)showDetail(b.dataset.detail);if(b?.dataset.save)toggleSave(b.dataset.save)});
$('#detail').addEventListener('click',e=>{const b=e.target.closest('[data-save]');if(b)toggleSave(b.dataset.save)});
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;render()}));
$('#search').addEventListener('input',e=>{state.query=e.target.value;render()});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;render()});$('#saved-filter').addEventListener('click',()=>{state.savedOnly=!state.savedOnly;render()});$('#nav-saved').addEventListener('click',()=>{state.savedOnly=true;state.category='全部';state.query='';$('#search').value='';render();$('#gallery').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});$('#reset').addEventListener('click',()=>{Object.assign(state,{category:'全部',query:'',savedOnly:false,sort:'curated'});$('#search').value='';$('#sort').value='curated';render();$('.filter').focus()});$('#about-button').addEventListener('click',()=>$('#about').showModal());document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});});document.addEventListener('keydown',e=>{if(e.key==='/'&&!document.querySelector('dialog[open]')&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}});render();
