export const cases = [
{id:'linear',name:'Linear',category:'产品设计',tags:['深色','产品叙事','秩序感'],url:'https://linear.app/',subtitle:'让复杂协作，回归清晰。',note:'以任务协作产品为观察对象，练习如何把密集的信息整理成清晰的优先级。关注产品价值、功能分组和行动入口之间的关系。',lesson:'先梳理信息层级，再决定视觉重量。',color:'#a7a8ef',art:'linear',headline:'Less noise.\nMore progress.',small:'WORK, BEAUTIFULLY ALIGNED.'},
{id:'stripe',name:'Stripe',category:'产品设计',tags:['色彩','金融科技','信息层级'],url:'https://stripe.com/',subtitle:'把复杂的商业，讲得明白。',note:'金融基础设施涉及多种产品与使用场景。以 Stripe 为例，研究如何从用户目标出发组织内容，让不同体量的企业找到自己的入口。',lesson:'让抽象能力落在具体的使用场景中。',color:'#fcbaa0',art:'stripe',headline:'Ideas into\npossibilities.',small:'A STUDY IN COLOR & COMMERCE'},
{id:'framer',name:'Framer',category:'创意设计',tags:['排版','创作工具','表现力'],url:'https://www.framer.com/',subtitle:'把脑海里的画面，变成网站。',note:'建站工具需要同时展示创作空间与操作能力。浏览 Framer 时，留意作品示例如何帮助读者想象自己能完成什么。',lesson:'好的展示既呈现结果，也激发行动。',color:'#dde67d',art:'framer',headline:'Make room\nfor bold ideas.',small:'DESIGN IS A WAY OF SEEING'},
{id:'vercel',name:'Vercel',category:'开发工具',tags:['极简','网格','开发体验'],url:'https://vercel.com/',subtitle:'从想法出发，向世界发布。',note:'以开发者平台为对象，研究技术内容如何按部署、基础设施和团队工作流组织。尝试用少量视觉元素突出一个明确的行动。',lesson:'克制不是空白，而是选择。',color:'#e4e4e3',art:'vercel',headline:'Build.\nShip. Repeat.',small:'AN EXPLORATION OF STRUCTURE'},
{id:'notion',name:'Notion',category:'效率工具',tags:['留白','模块化','工作空间'],url:'https://www.notion.com/',subtitle:'为想法，找一个生长的地方。',note:'多功能工作空间容易让新用户迷失。观察 Notion 如何围绕日常任务解释不同功能，再思考自己的产品是否也能以任务而非功能名导航。',lesson:'用熟悉的任务，解释陌生的能力。',color:'#e8dcc6',art:'notion',headline:'A little space.\nA lot of ideas.',small:'NOTES ON EVERYDAY CREATIVITY'},
{id:'raycast',name:'Raycast',category:'效率工具',tags:['深色','快捷操作','聚焦'],url:'https://www.raycast.com/',subtitle:'少一点操作，多一点心流。',note:'快捷工具的核心是降低动作成本。研究如何通过短路径、可搜索的功能和明确的键盘提示，帮助用户快速完成一个任务。',lesson:'好用的交互，让下一步自然发生。',color:'#fd846c',art:'raycast',headline:'In your flow.\nAt your fingertips.',small:'SMALL ACTIONS. BIG MOMENTUM.'},
{id:'arc',name:'Arc',category:'产品设计',tags:['柔和色彩','浏览器','亲和力'],url:'https://arc.net/',subtitle:'换个视角，重新遇见互联网。',note:'浏览器是高频而熟悉的工具。以 Arc 为观察对象，思考一个成熟产品类别如何通过情绪、语言与视觉重新建立用户期待。',lesson:'新鲜感，也可以来自熟悉事物的新视角。',color:'#aecbbe',art:'arc',headline:'A different\npoint of view.',small:'A WINDOW INTO POSSIBILITY'},
{id:'awwwards',name:'Awwwards',category:'创意设计',tags:['大字排版','作品展示','策展'],url:'https://www.awwwards.com/',subtitle:'让优秀作品，拥有自己的舞台。',note:'设计奖项与作品平台需要处理大量视觉内容。观察其作品入口与元信息，再思考缩略图、分类和作者信息各自应该承担的角色。',lesson:'作品是主角，导航负责把舞台让出来。',color:'#b7cbd7',art:'awwwards',headline:'Beyond\nthe ordinary.',small:'A CELEBRATION OF DIGITAL CRAFT'},
{id:'supabase',name:'Supabase',category:'开发工具',tags:['深色','技术产品','结构化'],url:'https://supabase.com/',subtitle:'让构建产品，少一点阻力。',note:'数据库开发平台的能力层次较多。阅读其产品分类，练习在一页中区分核心价值、能力证明与深入文档的入口。',lesson:'先建立理解，再展开技术细节。',color:'#8dcdb0',art:'supabase',headline:'The next thing\nstarts here.',small:'IDEAS NEED A FOUNDATION'},
{id:'resend',name:'Resend',category:'开发工具',tags:['单色','API','简洁'],url:'https://resend.com/',subtitle:'把一件事，做得足够清楚。',note:'邮件开发服务的主题十分明确。以 Resend 为例，思考如何围绕一个核心任务写标题、提供示例，并减少与主任务无关的内容。',lesson:'单一而清晰的主线，让表达更有力。',color:'#d0d0cc',art:'resend',headline:'Simple by\nintention.',small:'A NOTE ON CLARITY'},
{id:'astro',name:'Astro',category:'开发工具',tags:['内容优先','框架','速度'],url:'https://astro.build/',subtitle:'为内容而生，向速度而行。',note:'框架官网需要把技术选择与最终体验连接起来。观察 Astro 对内容站点和性能的表达，再尝试把技术优势转译为读者能理解的收益。',lesson:'不要只说技术是什么，也说它带来什么。',color:'#b6a3d6',art:'astro',headline:'Let your\ncontent shine.',small:'A SMALL STUDY OF INFINITE SPACE'},
{id:'shadcn',name:'shadcn/ui',category:'创意设计',tags:['组件','设计系统','可组合'],url:'https://ui.shadcn.com/',subtitle:'从小小组件，搭起完整体验。',note:'组件集合既是工具，也是设计系统的学习材料。研究控件状态、间距与组合方式，理解一致性如何在复杂界面中逐步建立。',lesson:'系统感，藏在每一个重复出现的细节里。',color:'#c9d1bd',art:'shadcn',headline:'Small pieces.\nBetter together.',small:'A LANGUAGE OF COMPONENTS'}
];
export function filterCases(items,{category='全部',query='',savedOnly=false,saved=[],sort='curated'}={}) {
 const q=query.trim().toLocaleLowerCase();const filtered=items.filter(c=>(category==='全部'||c.category===category)&&(!savedOnly||saved.includes(c.id))&&(!q||[c.name,c.category,c.subtitle,...c.tags].join(' ').toLocaleLowerCase().includes(q)));
 return sort==='name'?filtered.sort((a,b)=>a.name.localeCompare(b.name)):filtered;
}
